import { Laila } from 'next/font/google'
import SideMenu from "./components/sidemenu.js"
import styles from "./styles.css";

export const metadata = {
  title: "Goal Grid App",
  description: "Generated by create next app",
};

const laila = Laila({ subsets: ['latin'], weight: ['400', '700']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={laila.className}>
        {/*<div className="GoalGridAppLayout">*/}
          {/*<SideMenu/>*/}
          {children}
        {/*</div>*/}
      </body>
    </html>
  );
}
