import { Poppins } from 'next/font/google'

export const metadata = {
  title: "Goal Grid App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
